### ISSUE TITLE
Server crashes when creating block entities

### ISSUE THREAD

**Issue by SolidBlock-cn** [SolidBlock-cn/mishanguc#1]
在专用服务器上运行时，放置方块实体会崩溃。回溯堆栈如下：
```
[18:29:56] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ExceptionInInitializerError: null
        at pers.solid.mishang.uc.blockentity.HungSignBlockEntity.<init>(HungSignBlockEntity.java:50) ~[mishanguc-0.1.7-1.18.2.jar:?]
        at pers.solid.mishang.uc.block.HungSignBlock.method_10123(HungSignBlock.java:168) ~[mishanguc-0.1.7-1.18.2.jar:?]
        at net.minecraft.class_2818.method_12010(class_2818.java:265) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_30092(class_1937.java:211) ~[server-intermediary.jar:?]
        at net.minecraft.class_1937.method_8652(class_1937.java:196) ~[server-intermediary.jar:?]
        at net.minecraft.class_1747.method_7708(class_1747.java:159) ~[server-intermediary.jar:?]
        at net.minecraft.class_1747.method_7712(class_1747.java:76) ~[server-intermediary.jar:?]
        at net.minecraft.class_1747.method_7884(class_1747.java:50) ~[server-intermediary.jar:?]
        at net.minecraft.class_1799.method_7981(class_1799.java:250) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java:353) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1081) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:30) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:768) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:block_entity_type / mishanguc:hung_block_entity])
        at net.minecraft.class_2370.method_40274(class_2370.java:80) ~[server-intermediary.jar:?]
        at net.minecraft.class_2370.method_31051(class_2370.java:90) ~[server-intermediary.jar:?]
        at net.minecraft.class_2370.method_10273(class_2370.java:86) ~[server-intermediary.jar:?]
        at net.minecraft.class_2370.method_10272(class_2370.java:134) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.method_39197(class_2378.java:471) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.method_10230(class_2378.java:467) ~[server-intermediary.jar:?]
        at pers.solid.mishang.uc.blockentity.MishangucBlockEntities.<clinit>(MishangucBlockEntities.java:15) ~[mishanguc-0.1.7-1.18.2.jar:?]
        ... 27 more
```
以下为完整崩溃报告：
[crash-2022-04-11_18.29.57-server.txt](https://github.com/SolidBlock-cn/mishanguc/files/8463339/crash-2022-04-11_18.29.57-server.txt)

**Comment by SolidBlock-cn** [comment]
Fixed since 0.2.0.
