### ISSUE TITLE
混凝土扶手导致存档崩溃

### ISSUE THREAD

**Issue by Geonear** [SolidBlock-cn/mishanguc#13]
在一个自定义颜色的台阶下面放了一个simple_black_concrete_handrail_central，结果存档就打不开了。请问有没有什么解决方案或者原因分析？怕存档以后的建造过程中也不稳定。谢谢。以下是日志：
```
Description: Encountered exception while building chunk meshes

java.lang.IllegalArgumentException: **Cannot get property null as it does not exist in Block{mishanguc:simple_black_concrete_handrail_central}**
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at pers.solid.mishang.uc.block.HandrailCentralBlock.connectsIn(HandrailCentralBlock.java:207)
	at pers.solid.mishang.uc.block.HandrailStairBlock.method_9522(HandrailStairBlock.java:225)
	at net.minecraft.class_4970$class_4971.method_26187(class_4970.java:1024)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.BlockOcclusionCache.shouldDrawSide(BlockOcclusionCache.java:47)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer.isFaceVisible(BlockRenderer.java:94)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer.renderModel(BlockRenderer.java:74)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Geonear** [comment]
找到了稳定崩溃的场景，见图片。在这里放一个扶手就会崩溃。
![崩溃场景](https://github.com/user-attachments/assets/4b1fd587-b6cd-4fc3-9b5e-a4b4c14f7bf1)

**Comment by Geonear** [comment]
录了一个视频 方便的话可以在b站看看 谢谢 https://www.bilibili.com/video/BV1jn2aYkEZG/
