### ISSUE TITLE
使用mohist-1.20.1-Forge mod loading, version 47.3.11, for MC 1.20.1 with MCP 20230612.114412通过Sinytra Connector-1.0.0-beta.46+1.20.1运行Mishang Urban Construction-1.4.1-1.20.1出现错误

### ISSUE THREAD

**Issue by YwaLy** [SolidBlock-cn/mishanguc#15]
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:116)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.11/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.11/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103)
        at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.11/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        ... 8 more
Caused by: java.lang.ExceptionInInitializerError
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.commands.GameRuleCommand$1.handler$zck000$fabric_game_rule_api_v1$onRegisterCommand(GameRuleCommand.java:538)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.commands.GameRuleCommand$1.m_6889_(GameRuleCommand.java)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.GameRules.m_46166_(GameRules.java:149)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.GameRules.m_46203_(GameRules.java:144)
        at java.base/java.util.TreeMap.forEach(TreeMap.java:1319)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.GameRules.m_46164_(GameRules.java:143)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.commands.GameRuleCommand.m_137744_(GameRuleCommand.java:16)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.commands.Commands.<init>(Commands.java:164)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.ReloadableServerResources.<init>(ReloadableServerResources.java:41)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.ReloadableServerResources.m_247740_(ReloadableServerResources.java:75)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.WorldLoader.m_214362_(WorldLoader.java:38)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.lambda$main$2(Main.java:221)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.Util.m_214652_(Util.java:777)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.Util.m_214679_(Util.java:772)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Main.main(Main.java:220)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 13 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: no such field: net.minecraft.server.commands.GameRuleCommand$1.f_137760_/com.mojang.brigadier.builder.LiteralArgumentBuilder/getField
        at TRANSFORMER/fabric_game_rule_api_v1@1.0.40+683d4da877/net.fabricmc.fabric.impl.gamerule.GameRuleReflectionUtils.<clinit>(GameRuleReflectionUtils.java:40)
        ... 29 more
Caused by: java.lang.NoSuchFieldException: no such field: net.minecraft.server.commands.GameRuleCommand$1.f_137760_/com.mojang.brigadier.builder.LiteralArgumentBuilder/getField
        at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:912)
        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:989)
        at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3754)
        at java.base/java.lang.invoke.MethodHandles$Lookup.findVarHandle(MethodHandles.java:3202)
        at TRANSFORMER/fabric_game_rule_api_v1@1.0.40+683d4da877/net.fabricmc.fabric.impl.gamerule.GameRuleReflectionUtils.<clinit>(GameRuleReflectionUtils.java:38)
        ... 29 more
Caused by: java.lang.NoSuchFieldError: Class net.minecraft.server.commands.GameRuleCommand$1 does not have member field 'com.mojang.brigadier.builder.LiteralArgumentBuilder f_137760_'
        at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
        at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:957)
        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:986)
        ... 32 more

**Comment by SolidBlock-cn** [comment]
我注意到报错有如下内容```Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: no such field: net.minecraft.server.commands.GameRuleCommand$1.f_137760_/com.mojang.brigadier.builder.LiteralArgumentBuilder/getField```从后面的堆栈回溯来看，可能是Sinytra Connector的Fabric Gamerule API部分有点问题。因此我推测这可能是Sinyta Connector的问题。

**Comment by cdpyx** [comment]
对于这个问题我们做了一个临时的修复版本，可能迷上城建的版本比较落后，可以参考使用[https://github.com/RealmTech-Studio/Mishang-Urban-Construction-Mohisted](url)

**Comment by SolidBlock-cn** [comment]
该问题是否仍存在？我昨天测试了1.20.1的Sinatra Connector，结果发现没有问题。

**Comment by SolidBlock-cn** [comment]
如果问题依然存在，请重新开启此issue。
